# Chapter 2 - Preliminaries

## 2.1. Data Manipulation

### 2.1.1 Getting Started

In [1]:
import torch

In [2]:
# create a vector of 12 consecutive numbers and cast it to float32
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
# the total number of elements in the tensor
x.numel()

12

In [4]:
# the shape of the tensor
x.shape

torch.Size([12])

In [5]:
# change the size of the tensor from (12,) to (4, 3)
X = x.reshape(4, 3)
X

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

Given a tensor of size `(n,)` and target shape `(h, w)`, we know that `w = n/h`. To automatically infer one component of the shape, we can place a `-1` for the shape component that should be inferred automatically.

In [6]:
x.reshape(-1, 3)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [7]:
x.reshape(4, -1)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [8]:
# create a tensor of zeros with shape (2, 3, 4)
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
# create a tensor of ones with shape (2, 3, 4)
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
# create a tensor of random numbers from a standard Gaussian with shape (2, 3, 4)
torch.randn(2, 3, 4)

tensor([[[-0.6680,  0.4760, -0.8610,  0.8636],
         [ 0.5408, -0.4908,  2.8087, -0.2854],
         [-1.0068,  0.7742,  0.4477, -1.0036]],

        [[-0.4950, -0.0785,  0.1988,  0.2707],
         [-0.7737,  0.3649, -0.9622,  0.1571],
         [-0.2518, -0.6641, -0.2433, -0.7042]]])

In [11]:
# create a tensor with the exact values provided
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 2.1.2. Indexing and Slicing

In [12]:
# recall what X is
X

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [13]:
# select the last row
X[-1]

tensor([ 9., 10., 11.])

In [14]:
# select the second and third rows
X[1:3]

tensor([[3., 4., 5.],
        [6., 7., 8.]])

In [15]:
# change value
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., 17.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [16]:
# assign multiple elements the same value
X[:2, :] = 12
X

tensor([[12., 12., 12.],
        [12., 12., 12.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

### 2.1.3. Operations

In [17]:
# Recall what x is
x

tensor([12., 12., 12., 12., 12., 12.,  6.,  7.,  8.,  9., 10., 11.])

In [18]:
# exponential function
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969,    403.4288,   1096.6332,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [19]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

In [20]:
x + y

tensor([ 3.,  4.,  6., 10.])

In [21]:
x - y

tensor([-1.,  0.,  2.,  6.])

In [22]:
x * y

tensor([ 2.,  4.,  8., 16.])

In [23]:
x / y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [24]:
x ** y

tensor([ 1.,  4., 16., 64.])

In [25]:
# create two tensors with the same shape of (3, 4)
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [26]:
# concatenate two matrices along rows (dim=0)
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [27]:
# concatenate two matrices along columns (dim=1)
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [28]:
# construct a boolean tensor via logical statements
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [29]:
# sum up all the elements in the tensor
X.sum()

tensor(66.)

### 2.1.4. Broadcasting

Broadcasting works in the two following ways:
1. expand one or both arrays by copying eleemnts along axes with length 1 so that after this transformation, the two tensors have the same shape;
2. perform an elementwise operation on the resulting arrays.

In [30]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [31]:
# a + b still works
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

**Broadcasting** produces a *larger 3x2 matrix* by **replicating matrix `a` along the columns and matrix `b` along the rows before adding them elementwise.

### 2.1.5. Saving Memory

In [32]:
# recall X and Y
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [33]:
before = id(Y)
Y = Y + X

In [34]:
# Y is assigned a new address
before, id(Y)

(2851257203264, 2851257223104)

This is undesirable because
1. We do not want to run around allocating memory unnecessarily all the time... **Whenever possible, we want to perform these updates in place**.
2. We want to point at the same parameters from multiple variables.

To perform in-place operations, we can assign the result of an operation to a previously allocated array Y by using slice notation: `Y[:] = <expression>`:

In [35]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))

id(Z): 2851235302752


In [36]:
Z[:] = X + Y
# Z is NOT assigned a new address
print('id(Z):', id(Z))

id(Z): 2851235302752


If `X` is not reused in subsequent computation, we can also use `X[:] = X + Y` or `X += Y` to reduce the memory overhead of the operation:

In [37]:
before = id(X)
X += Y

In [38]:
before, id(X)

(2851259853056, 2851259853056)

### 2.1.6. Conversion to Other Python Objects

In [39]:
# recall X
X

tensor([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]])

In [40]:
# convert a tensor to a numpy array
A = X.numpy()
# convert a numpy array to a tensor
B = torch.from_numpy(A)

type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [41]:
# convert a size-1 tensor to a Python scalar
a = torch.tensor([3.5])
a

tensor([3.5000])

In [42]:
a.item()

3.5

In [43]:
float(a)

3.5

In [44]:
int(a)

3

## 2.2. Data Preprocessing

### 2.2.1. Reading the Dataset

In [55]:
# create a csv file
import os
# create a folder named data if it does not exist
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
# create a csv file in the folder data with the name house_tiny.csv if it does not exist
data_file = os.path.join('..', 'data', 'house_tiny.csv')

# write the csv file with the following content
with open(data_file, 'w') as f:
    f.write('''
NumRooms, RoofType, Price
NA, NA, 127500
2, NA, 106000
4, Slate, 178100
NA, NA, 140000
            ''')

In [56]:
import pandas as pd

data = pd.read_csv(data_file)
data

NumRooms  RoofType   Price
0       NaN        NA  127500
1       2.0        NA  106000
2       4.0     Slate  178100
3       NaN        NA  140000

### 2.2.2. Data Preparation

In [57]:
# split inputs and targets using iloc
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs, targets

(   NumRooms  RoofType
 0       NaN        NA
 1       2.0        NA
 2       4.0     Slate
 3       NaN        NA,
 0    127500
 1    106000
 2    178100
 3    140000
 Name:  Price, dtype: int64)

In [58]:
# imputation heuristics for NA
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms   RoofType_ NA   RoofType_ Slate   RoofType_nan
0       NaN           True             False          False
1       2.0           True             False          False
2       4.0          False              True          False
3       NaN           True             False          False

This treats `NaN` as a category.

In [59]:
# replacement heuristics for NA
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms   RoofType_ NA   RoofType_ Slate   RoofType_nan
0       3.0           True             False          False
1       2.0           True             False          False
2       4.0          False              True          False
3       3.0           True             False          False

### 2.2.3. Conversion to the Tensor Format

In [60]:
# convert inputs and targets to tensors once they are all numerical
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[3., 1., 0., 0.],
         [2., 1., 0., 0.],
         [4., 0., 1., 0.],
         [3., 1., 0., 0.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

## 2.3. Linear Algebra

### 2.3.1. Scalars

Scalars are implemented as tensors that contain only one element in PyTorch.

In [62]:
x = torch.tensor(3.)
y = torch.tensor(2.)
x,y

(tensor(3.), tensor(2.))

In [63]:
x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

### 2.3.2. Vectors

Vectors are implemented as 1st-order tensors in PyTorch.

In [64]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [65]:
x[2], len(x), x.shape

(tensor(2), 3, torch.Size([3]))

The *Order* is referred to the number of axes and the *dimensionality* is referred to the number of components.

Therefore, scalars are 0th-order tensors and vectors are 1st-order tensors.

### 2.3.3. Matrices

Matrices are 2nd-order tensors.

In [66]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [67]:
# to flip the axes, use transpose
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [68]:
# check whether two tensors are equal
A = torch.tensor([[1,2,3], [2,0,4], [3,4,5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### 2.3.4. Tensors

Each image arrives as a 3rd-order tensor with axes corresponding to the height, width, and channel. At each spatial location, the intensities of each color (red, green, and blue) are stacked along the channel.

A collection of images is represented in code by a 4th-order tensor, where distinct images are indexed along the first axis.

In [69]:
# create a 3rd-order tensor
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 2.3.5. Basic Properties of Tensor Arithmetic

In [70]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)

In [71]:
# assgin a copy of A to B by allocating new memory
B = A.clone()

In [72]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [73]:
A + B

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])

In [74]:
# elementwise multiplication (Hadamard product)
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [75]:
# adding/multiplying a scalar to a tensor does not change the shape
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### 2.3.6. Reduction

In [77]:
x = torch.arange(3, dtype=torch.float32)
x

tensor([0., 1., 2.])

In [78]:
# sum up all the elements in the tensor
x.sum()

tensor(3.)

In [79]:
# recall A
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [80]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

By Default, invoking the sum function *reduces* a tensor along all of its axes, eventually producing a scalar.

In [81]:
# sum over all elements along the rows (axis 0)
A.shape, A.sum(axis=0).shape, A.sum(axis=0)

(torch.Size([2, 3]), torch.Size([3]), tensor([3., 5., 7.]))

Since the input matrix reduces along axis 0 to genereate the output vector, this axis is missing from the shape of the output.

In [82]:
# sum over all elements along the columns (axis 1)
A.shape, A.sum(axis=1).shape, A.sum(axis=1)

(torch.Size([2, 3]), torch.Size([2]), tensor([ 3., 12.]))

In [83]:
# sum over all elements along both rows and columns
A.sum(axis=[0, 1]) == A.sum() # same as A.sum()

tensor(True)

In [84]:
# mean
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [85]:
# mean along rows
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

### 2.3.7. Non-Reduction Sum

Keep the number of axes unchanged when invoking the function for calculating the sum or mean.

In [88]:
# recall A
A, A.shape

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]))

In [86]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [89]:
# compare the difference
sum_A.shape, A.sum(axis=1).shape

(torch.Size([2, 1]), torch.Size([2]))

Since `sum_A` keeps its two axes after summing each row,we can divide `A` by `sum_A` with broadcasting to create a matrix where each row sums up to 1:

In [90]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

The `cumsum` function does not reduce the input tensor along any axis.

In [91]:
# calculate the cumulative sum of elements of A along axis 0
A.cumsum(axis=0), A.cumsum(axis=0).shape

(tensor([[0., 1., 2.],
         [3., 5., 7.]]),
 torch.Size([2, 3]))

### 2.3.8. Dot Products

Also known as *inner product*..

In [92]:
# recall x
x

tensor([0., 1., 2.])

In [93]:
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [94]:
# equivalently, this is the same as an elementwise multiplication and then a sum
torch.sum(x * y)

tensor(3.)

Applications of the dot products:
1. the weighted sum of a vector $\mathbf{x}$ with a set of weights $\mathbf{w}$ is $\mathbf{x}^T\mathbf{w}$;
2. when the weights are nonnegative and sum to 1, the dot product is a *weighted average*.
3. after normalizing two vectors to have unit length, the dot products express the cosine of the angle between them.

### 2.3.9. Matrix-Vector Products

Given a matrix in terms of its row vectors,
\begin{split}
\mathbf{A}=
\begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_m \\
\end{bmatrix}
\end{split}
where each $\mathbf{a}^\top_{i} \in \mathbb{R}^n$ is a row vector representing the i-th row of the matrix $\mathbf{A}$.

The matrix-vector product $\mathbf{Ax}$ is,
\begin{split}
\mathbf{A}=
\begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_m \\
\end{bmatrix}\mathbf{x}=
\begin{bmatrix}
\mathbf{a}^\top_{1}\mathbf{x} \\
\mathbf{a}^\top_{2}\mathbf{x} \\
\vdots \\
\mathbf{a}^\top_m\mathbf{x} \\
\end{bmatrix}
\end{split}

The matrix $\mathbf{A}$ can be thought of as a transformation projecting vectors from $\mathbb{R}^n$ to $\mathbb{R}^m$.

Matrix-vector proudcts describe the key calculation involved in computing the outputs of ecah layer in neural network given the outputs from the previous ayer.

In [95]:
# recall A and x
A, x

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]))

In [96]:
# matrix-vector product using PyTorch
torch.mv(A, x)

tensor([ 5., 14.])

The column dimension of `A` (its length along axis 1) must be the same as the dimension of `x` (its length).

The operator `@` can execute both matrix-vector and maxtrix-matrix products:

In [97]:
# matrix-vector product using Python @ operator
A @ x

tensor([ 5., 14.])

### 2.3.10. Matrix-Matrix Multiplication

Suppose there are two matrices $\mathbf{A} \in \mathbb{R}^{n \times k}$ and $\mathbf{B} \in \mathbb{R}^{k \times m}$,

\begin{split}
\mathbf{A}=
\begin{bmatrix}
 a_{11} & a_{12} & \cdots & a_{1k} \\
 a_{21} & a_{22} & \cdots & a_{2k} \\
\vdots & \vdots & \ddots & \vdots \\
 a_{n1} & a_{n2} & \cdots & a_{nk} \\
\end{bmatrix}
,\quad
\mathbf{B}=
\begin{bmatrix}
 b_{11} & b_{12} & \cdots & b_{1m} \\
 b_{21} & b_{22} & \cdots & b_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
 b_{k1} & b_{k2} & \cdots & b_{km} \\
\end{bmatrix}
\end{split}

or

\begin{split}
\mathbf{A}=
\begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_n \\
\end{bmatrix},
\quad 
\mathbf{B}=
\begin{bmatrix}
 \mathbf{b}_{1} & \mathbf{b}_{2} & \cdots & \mathbf{b}_{m} \\
\end{bmatrix}
\end{split}

The matrix product $\mathbf{C} \in \mathbb{R}^{n \times m}$ is,

\begin{split}
\mathbf{C} = 
\mathbf{AB} = 
\begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_n \\
\end{bmatrix}

\begin{bmatrix}
 \mathbf{b}_{1} & \mathbf{b}_{2} & \cdots & \mathbf{b}_{m} \\
\end{bmatrix}
= \begin{bmatrix}
\mathbf{a}^\top_{1} \mathbf{b}_1 & \mathbf{a}^\top_{1}\mathbf{b}_2& \cdots & \mathbf{a}^\top_{1} \mathbf{b}_m \\
 \mathbf{a}^\top_{2}\mathbf{b}_1 & \mathbf{a}^\top_{2} \mathbf{b}_2 & \cdots & \mathbf{a}^\top_{2} \mathbf{b}_m \\
 \vdots & \vdots & \ddots &\vdots\\
\mathbf{a}^\top_{n} \mathbf{b}_1 & \mathbf{a}^\top_{n}\mathbf{b}_2& \cdots& \mathbf{a}^\top_{n} \mathbf{b}_m
\end{bmatrix}
\end{split}



In [100]:
# recall A
A, A.shape

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]))

In [104]:
B = torch.ones(3, 4, dtype=torch.float32)
B, B.shape

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.Size([3, 4]))

In [105]:
# matrix-matrix multiplication using PyTorch
torch.mm(A, B)

tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])

In [106]:
# matrix-matrix multiplication using Python @ operator
A @ B

tensor([[ 3.,  3.,  3.,  3.],
        [12., 12., 12., 12.]])

### 2.3.11. Norms

The $\ell_2$ norm measure the (Euclidean) length of a vector, and it is expressed as

\begin{equation}
\|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^n x_i^2}.
\end{equation}

In [109]:
# compute the L2 norm of a vector
u = torch.tensor([3., -4.])
torch.norm(u)

tensor(5.)

The $\ell_1$ norm is the Mahanttan distance expressed as

\begin{equation}
\|\mathbf{x}\|_1 = \sum_{i=1}^n \left|x_i \right|.
\end{equation}

Compared to the $\ell_2$ norm, it is less sensitive to outliers.

In [110]:
# compute the L1 norm
torch.abs(u).sum()

tensor(7.)

The general $\ell_p$ norm:

\begin{equation}
\|\mathbf{x}\|_p = \left(\sum_{i=1}^n \left|x_i \right|^p \right)^{1/p}
\end{equation}

The *Frobenius norm* is easier to compute and defined as:

\begin{equation}
\|\mathbf{X}\|_\textrm{F} = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}.
\end{equation}
and it behaves as if it were an $\ell_2$ norm of a matrix-shaped vector.

In [111]:
torch.norm(torch.ones((4, 9)))

tensor(6.)